steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gitea.marrinus.trade/thelonesomeprogrammer/mqttcaster
      dockerfile: Dockerfile
      platforms: linux/amd64
      registry: gitea.marrinus.trade
      username:
        from_secret: gittea_user
      password:
        from_secret: gittea_pass
