steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gitea.marrinus.trade/thelonesomeprogrammer/mqttcaster
      dockerfile: Dockerfile
      platforms: linux/amd64
      registry: gitea.marrinus.trade
      password: Marrinus1
      username: thelonesomeprogrammer
